### ISSUE TITLE
Function to upload local csv to new google sheet

### ISSUE THREAD

**Issue by jennybc** [jennybc/gspreadr#54]
From #1, which was about a different thing, but accumulated some good links about this.

@leeper pointed out this: uploading using [the Drive API (specifically the file insert endpoint, using the `convert = true` argument)](https://developers.google.com/drive/v2/reference/#Files)

More links I found:

http://stackoverflow.com/questions/12765813/upload-csv-to-google-drive-spreadsheet-using-drive-v2-api

https://developers.google.com/drive/v2/reference/files/insert

**Comment by jennybc** [comment]
Done via b707de5460702e21bb154d27f5a6f15f04df9372

**Comment by yeedle** [comment]
Is it possible to extendin this to upload a dataframe directly to google sheets? Perhaps by invisibly writing dataframe to disk, uploading file to googlesheets, and then invisibly remove file from disk. I often find myself writing arbitrary dfs to disk just so that I can then upload them via `gs_upload`

**Comment by jennybc** [comment]
`gs_new()` can put an existing R object into a new Sheet.

https://cran.r-project.org/web/packages/googlesheets/vignettes/basic-usage.html#create-a-new-google-sheet

**Comment by yeedle** [comment]
Completely missed that 🙈
