### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by noamross** [jennybc/gspreadr#58]
Excellent work!

1) The OAuth implementation is really nice and clean.  @Ironholds, we should have `driver` do the same thing: store the app credentials in the package in `.onLoad()`, and store the user credentials in the package namespace.

2) I find the `print` and `str` methods for registered spreadsheets a little unintuitive.  I expect `str` to give me the actual structure of the R object, but in this case it converts.  `print(ss)`, though, just gives the same output one would get if the spreadsheet were a list.   I think the `str` method should be a `print` method.

3) I wonder if you want the "spreadsheet" class to be a "gspreadsheet" class or something like it.  I don't know if other packages have a "spreadsheet" class, but this would ensure the name is pretty specific, which would be useful for other packages using this class.  (e.g., `driver` could take an object of class "gspreadsheet" for a number of functions).

**Comment by jennybc** [comment]
Thanks @noamross!

We don't have a print method for spreadsheets, which explains why you're just getting the list behaviour. Since a spreadsheet object has virtually nothing a user cares about, I didn't really know what the print method should do. We had one at some point then realized there was ~90% overlap in the code for the print and str methods. So we dropped print and kept str.

Are you suggesting we make the current str behaviour the behaviour of a print method? And then drop str? Or can you think of two distinct things people might want for inspection of such an object? I could not.

Good idea about the `gspreadsheet` class. I'll do that today. At this point, an easy switch.

**Comment by noamross** [comment]
Yup, I'm suggesting the current str behavior be the print method, and drop str.spreadsheet.  I can't think of what a different str behavior would be. Custom print methods seem to be much more common than custom str methods.

**Comment by Ironholds** [comment]
I like both bits of this plan (storing credentials in that fashion, and integrating with gspreadsheet-class objects). Will open issues! The current blocker is I'm reluctant to do substantial development until your changes are merged, because I don't want to leave your code hanging.
